---
title: " WGNSSK tables for had.27.46a20"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document:
    reference_docx: boot/data/reportTemplate_2024_tables.docx
  mathjax: yes
  pdf_document: default

---


```{r setup, echo=FALSE, include=FALSE}

### General settings ###

library(knitr)
library(icesAdvice)
library(icesTAF)
library(tidyverse)
# library(pander)
# library(ggplot2)
# library(reshape2)
library(FLCore)
# library(png)
# library(magrittr)
library(flextable) 

# set global flextable layout
set_flextable_defaults(
  font.family = "Calibri",
  hansi.family = "Calibri",
  cs.family = "Calibri",
  font.size = 8.5,
  theme_fun = "theme_vanilla",
  big.mark = "", # no 1000 seperator
)

ay <- 2026
caption_prefix <- "Haddock in Subarea 4, Division 6.a and Subdivision 20. "

knitr::opts_chunk$set(cache=FALSE,echo=FALSE, warning=FALSE,
                      message=FALSE,progress=FALSE,verbose=FALSE,
                      include=TRUE,dev='png',autodep=FALSE,
                      tab.cap.style="Caption") #, fig.width=12, fig.height=8

numtab_formatting_stuff <- function(ft) {bg(ft, part = "header",bg = "#B7D1C3") %>% set_table_properties(width = 1, layout = "autofit")}
bioltab_formatting_stuff <- function(ft) {numtab_formatting_stuff(ft) %>% colformat_double(j=-1,digits=3) }

```  

# Catch data

```{r catch-num-wts, echo=FALSE}

load("data/stockData.RData")

## numbers at age
get_num_at_age <- function(x){
  dat <- as.data.frame(x)
  dat <- pivot_wider(dat,id_cols="year",names_from="age",values_from="data")
  dat <- dat %>% filter(year < ay)
  tmp <- dat %>% group_by(year) %>% summarise("8+" = sum(across(as.character(8:15))))
  dat <- left_join(dat,tmp, by="year")
  colnames(dat) <- gsub("15","15+",colnames(dat))
  dat <- round(dat)
  return(dat)
}

# catch 
dat <- get_num_at_age(stock.data65@catch.n)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.6. ",caption_prefix,"Numbers at age data (thousands) for total catch. Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment."))
ft <- numtab_formatting_stuff(ft)
ft


# landings
dat <- get_num_at_age(stock.data65@landings.n)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.7. ",caption_prefix,"Numbers at age data (thousands) for landings. Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment."))
ft <- numtab_formatting_stuff(ft)
ft

# discards
dat <- get_num_at_age(stock.data65@discards.n)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.8. ",caption_prefix,"Numbers at age data (thousands) for discards. Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment."))
ft <- numtab_formatting_stuff(ft)
ft

# bms landings
dat <- get_num_at_age(bmsn)
dat <- dat %>% filter(year>=2016)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.9. ",caption_prefix,"Numbers at age data (thousands) for BMS landings. Ages 0-7 and 8+ and years 2016-",ay-1," are used in the assessment."))
ft <- numtab_formatting_stuff(ft)
ft

# ibc
dat <- get_num_at_age(ibcn)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.10. ",caption_prefix,"Numbers at age data (thousands) for IBC. Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment."))
ft <- numtab_formatting_stuff(ft)
ft

## weights at age
get_biols_at_age <- function(x){
  dat <- as.data.frame(x)
  dat <- pivot_wider(dat,id_cols="year",names_from="age",values_from="data")
  dat <- dat %>% filter(year < ay)
  return(dat)
}

add_biols_at_age.pg <- function(x,dat){
  pg <- as.data.frame(x)
  pg$data[is.na(pg$data)] <- 0
  pg <- pg %>% filter(year < ay & age==8)
  pg <- pivot_wider(pg,id_cols="year",names_from="age",values_from="data")
  colnames(pg)[2] <- "8+"
  dat <- left_join(dat,pg, by="year")
  colnames(dat) <- gsub("15","15+",colnames(dat))
  dat <- round(dat,3)
  return(dat)
}

# catch 
dat <- get_biols_at_age(stock.data65@catch.wt)
dat <- add_biols_at_age.pg(stock.data65.pg@catch.wt,dat)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.11. ",caption_prefix,"Mean weight at age data (kg) for total catch. Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment."))
ft <- bioltab_formatting_stuff(ft)
ft


# landings
dat <- get_biols_at_age(stock.data65@landings.wt)
dat <- add_biols_at_age.pg(stock.data65.pg@landings.wt,dat)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.12. ",caption_prefix,"Mean weight at age data (kg) for landings. Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment."))
ft <- bioltab_formatting_stuff(ft)
ft

# discards
dat <- get_biols_at_age(stock.data65@discards.wt)
dat <- add_biols_at_age.pg(stock.data65.pg@discards.wt,dat)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.13. ",caption_prefix,"Mean weight at age data (kg) for discards. Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment."))
ft <- bioltab_formatting_stuff(ft)
ft

# bms landings
dat <- get_biols_at_age(bmsw)
dat <- add_biols_at_age.pg(bmsw.pg,dat)
dat <- dat %>% filter(year>=2016)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.14. ",caption_prefix,"Mean weight at age data (kg) for BMS landings. Ages 0-7 and 8+ and years 2016-",ay-1," are used in the assessment."))
ft <- bioltab_formatting_stuff(ft)
ft

# ibc
dat <- get_biols_at_age(ibcw)
dat <- add_biols_at_age.pg(ibcw.pg,dat)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.15. ",caption_prefix,"Mean weight at age data (kg) for IBC. Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment."))
ft <- bioltab_formatting_stuff(ft)
ft



```

# Biological parameters

```{r biols, echo=FALSE}

## biologicals

# stock weight at age
dat <- get_biols_at_age(stock.data65@stock.wt)
dat <- add_biols_at_age.pg(stock.data65.pg@stock.wt,dat)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.16. ",caption_prefix,"Mean weight at age data (kg) for the stock. Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment."))
ft <- bioltab_formatting_stuff(ft)
ft

# natural mortality
dat <- get_biols_at_age(stock.data65@m)
dat <- add_biols_at_age.pg(stock.data65.pg@m,dat)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.17. ",caption_prefix,"Estimates of natural mortality from the most recent key run of SMS (ICES WGSAM, 2023). Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment. *values since 2022 are set equal to 2022 values until the next SMS key run in completed by WGSAM."))
ft <- bioltab_formatting_stuff(ft)
ft


# maturity
dat <- get_biols_at_age(stock.data65@mat)
dat <- add_biols_at_age.pg(stock.data65.pg@mat,dat)
colnames(dat) <- gsub("year"," ",colnames(dat))

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.18. ",caption_prefix,"Estimates of the proportion mature-at-age. Ages 0-7 and 8+ and years 1972-",ay-1," are used in the assessment."))
ft <- bioltab_formatting_stuff(ft)
ft



```

# Surveys
```{r surveys, echo=FALSE}

## surveys

load(paste0("boot/data/Input data - WGNSSK ",ay,"/indices.RData"))

# modelled indices

# Q1
dat <- x.idx[[1]]
dat <- as.data.frame(dat@index)
dat <- pivot_wider(dat,id_cols="year",names_from="age",values_from="data")
dat$year <- 1

# add header info
dat.h <- as.data.frame(dat[1:3,])
dat.h[] <- NA
dat.h[1,1:2] <- c(1983,ay)
dat.h[2,1:4] <- c(1,1,0,0.25)
dat.h[3,1:2] <- c(1,8)

dat <- bind_rows(dat.h,dat)

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.19. ",caption_prefix,"Data available for calibration of the assessment. Only those data used in the final assessment are shown here."))

# sort header
ft <- delete_rows(ft, i = 1, part = "header")
ft <- add_header_lines(x = ft, values = c("Delta-GAM NS-WC Q1"))

# format
ft <- bg(ft, part = "header",bg = "#B7D1C3") %>% set_table_properties(width = 1, layout = "autofit")
ft <- ft %>% colformat_double(i=c(1:3),digits=0)  %>% bold(part="header")
ft 

# Q3+Q4
dat <- x.idx[[2]]
dat <- as.data.frame(dat@index)
dat <- pivot_wider(dat,id_cols="year",names_from="age",values_from="data")
dat$year <- 1

# add header info
dat.h <- as.data.frame(dat[1:3,])
dat.h[] <- NA
dat.h[1,1:2] <- c(1991,ay-1)
dat.h[2,1:4] <- c(1,1,0.5,1)
dat.h[3,1:2] <- c(0,8)

dat <- bind_rows(dat.h,dat)

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.2.19. (cont.) ",caption_prefix,"Data available for calibration of the assessment. Only those data used in the final assessment are shown here."))

# sort header
ft <- delete_rows(ft, i = 1, part = "header")
ft <- add_header_lines(x = ft, values = c("Delta-GAM NS-WC Q3+Q4"))

# format
ft <- bg(ft, part = "header",bg = "#B7D1C3") %>% set_table_properties(width = 1, layout = "autofit")
ft <- ft %>% colformat_double(i=c(1:3),digits=0)  %>% bold(part="header")
ft 
```

# Assessment outputs
```{r assessment-results, echo=FALSE}

## assessment

# parameter estimates
dat <- read.csv("output/SAM/tab_pars.csv",stringsAsFactors = F,colClasses = c("character",rep("numeric",5)))

# order columns
dat <- dat[,c(1,4,5,6,3,2)]
colnames(dat) <- c(" ","Estimate","Lower bound","Upper bound","sd(par)","log(par)")

# formatting indices
idx1 <- grep("logFpar",dat[,1])

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.3.3. ",caption_prefix,"SAM final assessment: Parameter estimates."))

# format
ft <- bg(ft, part = "header",bg = "#B7D1C3") %>% set_table_properties(width = 1, layout = "autofit")
ft <- ft %>% colformat_double(digits=3) %>% 
  colformat_double(i=idx1,j=c(2:4),digits=5)
ft

# F at age
dat <- read.csv("output/SAM/tab_fay.csv")
colnames(dat) <- gsub("X","",colnames(dat))

# calc mean F
tmp <- rowMeans(dat[,as.character(2:4)],na.rm=T)
dat <- cbind(dat,tmp)

#colnames
colnames(dat) <- gsub("Year"," ",colnames(dat))
colnames(dat) <- gsub("8","8+",colnames(dat))
colnames(dat) <- gsub("tmp","Mean F(2-4)",colnames(dat))


ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.3.4. ",caption_prefix,"Estimates of fishing mortality at age from the final SAM assessment. Estimates refer to the full year (January–December) except for age 0, for which the mortality rate given refers to the second half-year only (July–December)."))

# format
ft <- bg(ft, part = "header",bg = "#B7D1C3") %>% set_table_properties(width = 1, layout = "autofit")
ft <- ft %>% colformat_double(digits=3) 
ft

# N at age
dat <- read.csv("output/SAM/tab_numbers.csv")
colnames(dat) <- gsub("X","",colnames(dat))

#colnames
colnames(dat) <- gsub("Year"," ",colnames(dat))
colnames(dat) <- gsub("8","8+",colnames(dat))


ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.3.5. ",caption_prefix,"Estimates of stock numbers at age (thousands) from the final SAM assessment. Estimates refer to 1 January, except for age 0 for estimates refer to 1 July. *SAM estimated survivors and projected recruitment."))

# format
ft <- bg(ft, part = "header",bg = "#B7D1C3") %>% set_table_properties(width = 1, layout = "autofit")
ft <- ft %>% colformat_double(digits=0) 
ft

# stock assessment summary
dat <- read.csv("output/SAM/tab_summary.csv")

#colnames
colnames(dat) <- c("Year","Recruitment (age 0)","Recruitment low", "Recruitment high", "SSB estimate",
                   "SSB low", "SSB high", "Fbar (2-4)", "Fbar low", "Fbar high", "TSB estimate", "TSB low", "TSB high")

ft <- flextable(dat)
ft <- set_caption(ft, caption = paste0("Table 8.3.6. ",caption_prefix,"Stock summary table for the final SAM model. Both estimates and the 5th (low) and 95th (high) percentiles are given."))

# format
ft <- bg(ft, part = "header",bg = "#B7D1C3") %>% set_table_properties(width = 1, layout = "autofit")
ft <- ft %>% colformat_double(digits=0) %>% colformat_double(j=8:10, digits=3)
ft


```

# Forecast
```{r forecast, echo=FALSE}

## forecast

# inputs
dat1 <- read.table("output/Forecast/had.27.46a20 - Forecast weights - stock-at-age.txt")
dat2 <- read.table("output/Forecast/had.27.46a20 - Forecast weights - catch-at-age.txt")
dat3 <- read.table("output/Forecast/had.27.46a20 - Forecast weights - landings-at-age.txt")
dat4 <- read.table("output/Forecast/had.27.46a20 - Forecast weights - discards-at-age incl BMS and IBC.txt")
dat5 <- read.csv("output/Forecast/Forecast inputs table.csv")


dat.temp <- data.frame(Age=0:8,Mat=dat5$Mat,NM=dat5$NM,SWt=NA,CWt=NA,LWt=NA,DWt=NA,Sel=dat5$Sel,LF=dat5$LF)

# tab_per_year
tab_per_year <- function(yr,dat.temp){
  dat <- dat.temp
dat$SWt <- t(dat1[as.character(yr),])
dat$CWt <- t(dat2[as.character(yr),])
dat$LWt <- t(dat3[as.character(yr),])
dat$DWt <- t(dat4[as.character(yr),])


ft <- flextable(dat)
# format
ft <- add_header_row(x = ft, values = c(yr),colwidths = 9) 
ft <- bg(ft, i=1, part = "header",bg = "#B7D1C3") %>% set_table_properties(width = 1, layout = "autofit") %>%
  align(i=1,align="left",part="header")
ft <- ft %>% colformat_double(digits=3)
return(ft)
}


# data year
yr <- ay
ft <- tab_per_year(yr,dat.temp)
ft <- set_caption(ft, caption = paste0("Table 8.6.1. ",caption_prefix,"Short-term forecast inputs."))
ft

# int year
yr <- ay+1
ft <- tab_per_year(yr,dat.temp)
ft

# tac year
yr <- ay+2
ft <- tab_per_year(yr,dat.temp)
ft

# change in advice


```
\newpage
\clearpage
